# -*- coding: utf-8 -*-

##############################################################################
#a########  "قُلۡ بِفَضلِ ٱللَّهِ وَبِرَحمَتِهِۦ فَبِذَٰلِكَ فَليَفرَحُواْ هُوَ خَيرُُ مِّمَّا يَجمَعُونَ"  ########
##############################################################################


LANGUAGES_SCRABBLE = [
             'العربية',
             'Deutsch',
             'English',
             'Español',
             'Français',
             'Italiano',
             'Nederlands',
             'Русский',
             'հայերէն',
             'Afrikaans',
             'Ænglisc',
             'Bamana', 
             'Bikol',
             'Brezhoneg',
             'български',
             'Suomi',
             'Português - Brazil',
             'Český',
             'Euskara',
             'Nederlands',
             'Polski',
             'Srpski',
             'Català',
             'Hrvatski',
             'Dansk',
             'Esperanto',
             'Eesti',
             'Galego',
             'Ελληνικά',
             'Ayisyen',
             'Magyar',
             'Íslenska',
             'Indonesia',
             'Gaeilge',
             'ひらがな',
             'ローマ字',
             'Lătīna',
             'Latviešu',
             'Lietuvių',
             'Malagasy',
             'Norsk',
             'Polski',
             'Português',
             'Română',
             'Slovenčina',
             'Slovenščina',
             'Svenska',
             'Setswana',
             'Українська',
             'Cymraeg',
             '注音符號',
             'Melayu',
             'Türkçe',
             ]

LANGUAGES_SURFACE = [
            '< System >',
             'العربية',
             'Deutsch',
             'English',
             'Español',
             'Français',
             'Italiano',
             'Nederlands',
             'Русский',
             'Deutsch',
             ]

DICT_LANGUAGES_CODE = {
             'العربية': 'ar',
             'Deutsch': 'de',
             'English': 'en',
             'Español': 'es',
             'Français': 'fr',
             'Italiano': 'it',
             'Nederlands': 'nl',
             'Русский': 'ru',
             'հայերէն': 'hy',
             'Afrikaans': 'af',
             'Ænglisc': 'ang',
             'Bamana': 'bm', 
             'Bikol': 'bcl',
             'Brezhoneg': 'br',
             'български': 'bg',
             'Suomi': 'fi',
             'Português - Brazil': 'br',
             'Český': 'cs',
             'Euskara': 'eu',
             'Nederlands': 'nl',
             'Polski': 'pl',
             'Srpski': 'sr',
             'Català': 'ca',
             'Hrvatski': 'hr',
             'Dansk': 'da',
             'Esperanto': 'eo',
             'Eesti': 'et',
             'Galego': 'gl',
             'Ελληνικά': 'el',
             'Ayisyen': 'ht',
             'Magyar': 'hu',
             'Íslenska': 'is',
             'Indonesia': 'id',
             'Gaeilge': 'ga',
             'ひらがな': 'hira',
             'ローマ字': 'romaji',
             'Lătīna': 'la',
             'Latviešu': 'lv',
             'Lietuvių': 'lt',
             'Malagasy': 'mg',
             'Norsk': 'no',
             'Polski': 'pl',
             'Português': 'pt',
             'Română': 'ro',
             'Slovenčina': 'sk',
             'Slovenščina': 'sl',
             'Svenska': 'sv',
             'Setswana': 'tn',
             'Türkçe': 'tr',
             'Українська': 'uk',
             'Cymraeg': 'cy',
             '注音符號': 'bopo',
             'Melayu': 'ms',
             }

DICT_LANGUAGES_NAME = {
            'is': 'Íslenska',
            'bm': 'Bamana',
            'hr': 'Hrvatski',
            'sv': 'Svenska',
            'fi': 'Suomi',
            'tn': 'Setswana',
            'es': 'Español',
            'lv': 'Latviešu',
            'pl': 'Polski',
            'ca': 'Català',
            'cs': 'Český',
            'gl': 'Galego',
            'de': 'Deutsch',
            'romaji': 'ローマ字',
            'hira': 'ひらがな',
            'ms': 'Melayu',
            'it': 'Italiano',
            'lt': 'Lietuvių',
            'ro': 'Română',
            'bcl': 'Bikol',
            'hu': 'Magyar',
            'af': 'Afrikaans',
            'bopo': '注音符號',
            'pt': 'Português',
            'sr': 'Srpski',
            'la': 'Lătīna',
            'fr': 'Français',
            'bg': 'български',
            'mg': 'Malagasy',
            'da': 'Dansk',
            'uk': 'Українська',
            'id': 'Indonesia',
            'ga': 'Gaeilge',
            'et': 'Eesti',
            'br': 'Brezhoneg',
            'sk': 'Slovenčina',
            'eo': 'Esperanto',
            'ht': 'Ayisyen',
            'br': 'Português - Brazil',
            'ru': 'Русский',
            'ang': 'Ænglisc',
            'eu': 'Euskara',
            'el': 'Ελληνικά',
            'nl': 'Nederlands',
            'en': 'English',
            'sl': 'Slovenščina',
            'cy': 'Cymraeg',
            'hy': 'հայերէն',
            'tr': 'Türkçe',
            'ar': 'العربية',
            'no': 'Norsk',
             }

    
