#! /usr/bin/python3
# -*- coding: UTF-8 -*-

from site import addsitedir
addsitedir('/usr/local/share/GScrabble/modules')
addsitedir('/usr/share/GScrabble/modules')
addsitedir('./modules')

import gscrabble
gscrabble.main()
